server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/HistoryService

  application:
    name: history-service

  config:
    import: optional:configserver:http://localhost:8888/

  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"