spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888/

  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: default

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: "b6a4f2319dbde50cf2a1e476ec9f77e3d8c22148790c4e537103c0f77e3a6c42"
      expiration: 1209600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
